#!/usr/bin/env bash

if [ -z "$1" ] || ! [ -d "$1" ]; then
    echo "Not a valid directory"
    exit 1
fi

do_rsync() {
    rsync -rtv --exclude '.git' --exclude 'node_modules' --delete ./ "$1"
}

echo "You are about to rsync the current directory with \`$1\`. Are you sure you want to proceed?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) do_rsync "$1"; break;;
        No ) exit;;
    esac
done
